version: "3.7"
services:
  openfisca:
    build:
      context: ./
      dockerfile: ./Dockerfile
    volumes:
      - ${LOCAL_WORKSPACE_FOLDER:-.}:/app
    command: make serve-local
    user: user:user
    ports:
      - 5000:5000
    networks:
      - openfisca

networks:
  openfisca:
    name: openfisca
